package br.UFSC.GRIMA.util;

public class HeaderUtil {
	
	public static String changeHeader(String file21,String header){
		int headerIndex = file21.indexOf("/* Generated by software containing");
		file21.substring(0,headerIndex);
		file21.substring(headerIndex+158, file21.length());
		
		return file21.substring(0,headerIndex-1)+"\n /*" + header +"*/"+ file21.substring(headerIndex+164, file21.length());
	}

}
